app:
  providers:
    priceProvider: yahoo
    cwApiKey: CW_API_KEY
    ipApiKey: IP_API_KEY

  log:
    level: dcapal_backend=info,tower_http=debug
    file: dcapal.log
    enableStdout: true

server:
  web:
    hostname: 127.0.0.1
    port: 8080
  metrics:
    hostname: 127.0.0.1
    port: 9000
  redis:
    hostname: 127.0.0.1
    port: 6379